- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop webaap
   - name: remove container
     shell: docker container rm webaap
   - name: remove docker image
     shell: docker image rmi arshsra/webaap
   - name: create new container
     shell: docker container run -itd --name webaap -p 9000:80 arshsra/webaap
